export const SEARCHFIELD = 'SEARCHFIELD';

export const FIND_MOVIES_PENDING = 'FIND_MOVIES_PENDING';
export const FIND_MOVIES_SUCCESS = 'FIND_MOVIES_SUCCESS';
export const FIND_MOVIES_FAILURE = 'FIND_MOVIES_FAILURE';

export const FIND_COMEDIES_PENDING = 'FIND_COMEDIES_PENDING';
export const FIND_COMEDIES_SUCCESS = 'FIND_COMEDIES_SUCCESS';
export const FIND_COMEDIES_FAILURE = 'FIND_COMEDIES_FAILURE';

export const FIND_HISTORY_PENDING = 'FIND_HISTORY_PENDING';
export const FIND_HISTORY_SUCCESS = 'FIND_HISTORY_SUCCESS';
export const FIND_HISTORY_FAILURE = 'FIND_HISTORY_FAILURE';

export const FIND_HORROR_PENDING = 'FIND_HORROR_PENDING';
export const FIND_HORROR_SUCCESS = 'FIND_HORROR_SUCCESS';
export const FIND_HORROR_FAILURE = 'FIND_HORROR_FAILURE';

export const GET_MOVIE_DETAILS_PENDING = 'GET_MOVIE_DETAILS_PENDING';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';

export const GET_MOVIE_CREDITS_PENDING = 'GET_MOVIE_CREDITS_PENDING';
export const GET_MOVIE_CREDITS_SUCCESS = 'GET_MOVIE_CREDITS_SUCCESS';
export const GET_MOVIE_CREDITS_FAILURE = 'GET_MOVIE_CREDITS_FAILURE';
